name: Build and Deploy

on: [push, pull_request]

jobs:
  windows-build:

    name: windows-builder

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build Native Lib
        run: |
             cd simple_native_lib
             mkdir build
             cd build
             cmake ../
             cmake --build ./ -- /p:Configuration=Debug /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/gmodTestLib.dll
