name: Build and Deploy

on: [push, pull_request]

jobs:
  windows-builder:

    name: windows-builder

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build Native Lib
        run: |
             mkdir build
             cd build
             cmake ../simple_native_lib
             cmake --build ./ -- /p:Configuration=Debug /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/gmodTestLib.dll

  linux-builder:

    name: linux-builder

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build Native Lib
        run: |
             mkdir build
             cd build
             cmake ../simple_native_lib
             cmake --build ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/libgmodTestLib.so

  macos-builder:

    name: macos-builder

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build native Lib
        run: |
             mkdir build
             cd build
             cmake ../simple_native_lib
             cmake --build ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/libgmodTestLib.dylib

  nuget-packer:
    name: nuget-packer

    runs-on: ubuntu-latest

    needs: [windows-builder, builder, builder]

    steps:
      - name: Set up dotnet SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: '3.1.x'

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: packager/

      - name: Struct of folder
        run: |
             cd packager
             ls -a -R
