name: Build and Deploy

on: [push, pull_request]

jobs:
  windows-build:

    name: Windows build

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build Native Lib
        run: |
             cd simple_native_lib
             cmake ./
             cmake --build ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: ./gmodTestLib.dll
